### ISSUE TITLE
Falta de novidades

### ISSUE THREAD

**Issue by matheushw** [eduardoadoglio/tic-tac-toe-minimax#5]
Não sei se o problema ta com o `pull` do git ou se o repo não ta sendo atualizado mesmo. Acredito fortemente que seja um problema de colaboradores do repo não estarem dando updates.

No aguardo de novidades

**Comment by eduardoadoglio** [comment]
Resolvido com o PR [#6](https://www.youtube.com/watch?v=dQw4w9WgXcQ), agradeço pela contribuição pro projeto.
